# "Sign in with FruitScope" — confidential OIDC client credentials.
#
# The client secret is shared between two independently-managed systems: this
# Cloud Run service (OIDC_CLIENT_SECRET) and the OIDC provider's OAUTH_CLIENTS
# (registered in fruitscope-cluster-config). So it is provisioned out-of-band in
# Secret Manager — the same convention as the other fruitscope-prod-oauth-*
# secrets — and referenced here by name, rather than generated by Terraform
# (which would rotate it out from under the provider on every apply).
#
# Provision once (and register the SAME value in the provider's
# fruitscope-prod-oauth-clients secret):
#
#   S=$(openssl rand -hex 32)
#   printf '%s' "$S" | gcloud secrets create verdant-oidc-client-secret \
#     --data-file=- --replication-policy=automatic --project=braided-visitor-372321

data "google_secret_manager_secret" "oidc_client_secret" {
  secret_id = "verdant-oidc-client-secret"
}

resource "google_secret_manager_secret_iam_member" "runtime_oidc_secret" {
  secret_id = data.google_secret_manager_secret.oidc_client_secret.id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.runtime.email}"
}
